// +build autogen,!windows

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	ContainerdCommitID string = "03e5862ec0d8d3b3f750e19fca3ee367e13c090e"
	RuncCommitID       string = "51371867a01c467f08af739783b8beafc154c4d7"
	InitCommitID       string = "949e6facb77383876aeff8a6944dde66b3089574"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
